# Generated by Django 4.0.3 on 2022-10-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_delete_category_remove_post_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_choices', models.CharField(choices=[('축구', '축구'), ('농구', '농구'), ('배구', '배구'), ('야구', '야구'), ('테니스', '테니스'), ('배드민턴', '배드민턴'), ('산책/러닝', '산책/러닝')], default='축구', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.exercise'),
        ),
    ]
