# Generated by Django 4.0.3 on 2022-10-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_exercise_alter_post_id_post_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_choices',
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
