# Generated by Django 4.0.3 on 2022-10-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.TimeField(default=''),
        ),
    ]
