# Generated by Django 4.0.3 on 2022-10-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=''),
        ),
    ]
